name: CI

on:
  push:
    branches : main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check Prettier
        run: yarn prettier --check "src/**/*.{ts,tsx,js,jsx,json,md}"

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn tsc --noEmit

      - name: Build
        run: yarn build